[tool.poetry]
name = "aidevtools-hw1"
version = "0.1.0"
description = "Personal chore tracker homework project"
authors = ["sadevaraj"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.6"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
