# Generated by Django 5.2.17 on 2026-09-07 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly_target', 'Weekly target'), ('one_off', 'One-off')], default='daily', max_length=20)),
                ('weekly_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recurrence_type', 'weekly_target'), _negated=True), ('weekly_target__gte', 1), _connector='OR'), name='weekly_target_required_for_weekly_target'), models.CheckConstraint(condition=models.Q(models.Q(('recurrence_type', 'one_off'), _negated=True), ('due_date__isnull', False), _connector='OR'), name='due_date_required_for_one_off')],
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.chore')),
            ],
            options={
                'ordering': ['-completed_on', '-created_at'],
            },
        ),
    ]
