# Generated by Django 5.2.17 on 2026-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='completion',
            constraint=models.UniqueConstraint(fields=('chore', 'completed_on'), name='unique_completion_per_chore_per_day'),
        ),
    ]
